<?php

/**
 * Implementation of hook_menu()
 * 
 */
function portfolio_menu() {

    $items = array();

    $items['portfolio'] = array(
        'title' => 'Portfolio',
        'access arguments' => array('access content'),
        'page callback' => 'portfolio_default_page',
        'page arguments' => array(1),
        'type' => MENU_CALLBACK,
        'file' => 'portfolio.pages.inc',
    );

    return $items;
}

function portfolio_theme($existing, $type, $theme, $path) {
    return array(
        'portfolio_4c' => array(
            'variables' => array('nodes' => NULL),
            'template' => 'portfolio_4c',
        ),
        'portfolio_3c' => array(
            'variables' => array('nodes' => NULL),
            'template' => 'portfolio_3c',
        ),
        'portfolio_2c' => array(
            'variables' => array('nodes' => NULL),
            'template' => 'portfolio_2c',
        ),
    );
}

function portfolio_format_comma_field($field_category, $node, $link = TRUE, $limit = NULL) {
    $category_arr = array();
    $category = '';
    if (!empty($node->{$field_category}[LANGUAGE_NONE])) {
        foreach ($node->{$field_category}[LANGUAGE_NONE] as $item) {
            $term = taxonomy_term_load($item['tid']);
            if ($term) {
                if ($link) {
                    $category_arr[] = l($term->name, 'taxonomy/term/' . $item['tid']);
                } else {
                    $category_arr[] = $term->name;
                }
            }

            if ($limit) {
                if (count($category_arr) == $limit) {
                    $category = implode(', ', $category_arr);
                    return $category;
                }
            }
        }
    }
    $category = implode(', ', $category_arr);

    return $category;
}

function portfolio_format_terms($field_category, $node, $limit = NULL) {
  
    $category_arr = array();
    $category = '';
    if (!empty($node->{$field_category}[LANGUAGE_NONE])) {
        foreach ($node->{$field_category}[LANGUAGE_NONE] as $item) {
            $term = taxonomy_term_load($item['tid']);
            if ($term) {
                $category_arr[] = 'tid-' . $term->tid;
            }

            if ($limit) {
                if (count($category_arr) == $limit) {
                    $category = implode(' ', $category_arr);
                    return $category;
                }
            }
        }
    }
    $category = implode(' ', $category_arr);

    return $category;
}

