<?php

/*
 * Implementation of hook_block_info()
 */

function custom_block_info() {

  $blocks['recent_post'] = array(
      'info' => t('[custom] Recent content'),
          // DRUPAL_CACHE_PER_ROLE will be assumed.
  );
  $blocks['footer_from_the_blog'] = array(
      'info' => t('[custom] Footer from the blog'),
          // DRUPAL_CACHE_PER_ROLE will be assumed.
  );
  $blocks['sidebar_categories'] = array(
      'info' => t('[custom] Sidebar categories'),
          // DRUPAL_CACHE_PER_ROLE will be assumed.
  );

  $blocks['recent_projects'] = array(
      'info' => t('[custom] Recent Work'),
          // DRUPAL_CACHE_PER_ROLE will be assumed.
  );



  return $blocks;
}

function custom_block_configure($delta = '') {
  // This example comes from node.module.
  $form = array();
  switch ($delta) {
    case 'recent_post':

      $form['recent_post_block_count'] = array(
          '#type' => 'select',
          '#title' => t('Number of recent content items to display'),
          '#default_value' => variable_get('recent_post_block_count', 5),
          '#options' => drupal_map_assoc(array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 25, 30)),
      );

      break;
    case 'footer_from_the_blog':

      $form['footer_from_the_blog_count'] = array(
          '#type' => 'select',
          '#title' => t('Number of recent content items to display'),
          '#default_value' => variable_get('footer_from_the_blog_count', 2),
          '#options' => drupal_map_assoc(array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 25, 30)),
      );

      break;

    case 'recent_projects':

      $form['recent_projects_block_count'] = array(
          '#type' => 'select',
          '#title' => t('Number of items to display'),
          '#default_value' => variable_get('recent_projects_block_count', 9),
          '#options' => drupal_map_assoc(array(4, 8, 9, 10, 12, 16, 20, 24, 28, 32, 36, 40)),
      );

      break;
  }
  return $form;
}

function custom_block_save($delta = '', $edit = array()) {
  // This example comes from node.module.

  switch ($delta) {
    case 'recent_post':
      variable_set('recent_post_block_count', $edit['recent_post_block_count']);

      break;
    case 'footer_from_the_blog':
      variable_set('footer_from_the_blog_count', $edit['footer_from_the_blog_count']);

      break;

    case 'recent_projects':
      variable_set('recent_projects_block_count', $edit['recent_projects_block_count']);
      break;
  }
}

function custom_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {

    case 'recent_post':
      if (user_access('access content')) {
        $block['subject'] = t('Recent post');
        if ($nodes = _custom_recent_post_get_nodes(variable_get('recent_post_block_count', 5))) {
          $block['content'] = array(
              '#theme' => 'custom_recent_post',
              '#nodes' => $nodes,
          );
        } else {
          $block['content'] = t('No content available.');
        }
      }
      break;
    case 'footer_from_the_blog':
      if (user_access('access content')) {
        $block['subject'] = t('From the blog');
        if ($nodes = _custom_recent_post_get_nodes(variable_get('footer_from_the_blog_count', 2))) {
          $block['content'] = array(
              '#theme' => 'custom_footer_from_the_blog',
              '#nodes' => $nodes,
          );
        } else {
          $block['content'] = t('No content available.');
        }
      }
      break;

    case 'recent_projects':
      $node_limit = variable_get('recent_projects_block_count', 9);
      $content_type = 'portfolio';
      $query = db_query('SELECT n.nid FROM {node} n INNER JOIN {field_data_field_image} f ON f.entity_id = n.nid WHERE n.type = :type AND n.status = 1 ORDER BY n.created DESC LIMIT 0, ' . $node_limit, array(':type' => $content_type));
      $nids = $query->fetchCol();
      $nodes = node_load_multiple($nids);

      if (!empty($nodes)) {
        $block['content'] = array(
            '#theme' => 'recent_projects',
            '#nodes' => $nodes,
            '#title' => custom_block_get_title($delta),
        );
      }

      break;

    case 'sidebar_categories':
      $v_machine_name = 'blog_categories';
      $vocab = taxonomy_vocabulary_machine_name_load($v_machine_name);
      $vid = $vocab->vid;
      $terms = taxonomy_get_tree($vid);
      if (!empty($terms)) {
        $block['subject'] = t('Categories');
        $block['content'] = array(
            '#theme' => 'sidebar_categories',
            '#terms' => $terms,
        );
      }

      break;
  }
  return $block;
}

function _custom_recent_post_get_nodes($limit) {

  $node_type = 'blog'; // this is name of blog type content.
  $nodes = array();
  $nids = db_query("SELECT n.nid FROM {node} n WHERE n.status = 1 AND n.type = :type ORDER BY n.created DESC LIMIT 0," . $limit, array(':type' => $node_type))->fetchCol();
  if (!empty($nids)) {
    $nodes = node_load_multiple($nids);
  }
  return $nodes;
}

function custom_theme($existing, $type, $theme, $path) {
  return array(
      'custom_recent_post' => array(
          'variables' => array('nodes' => NULL),
          'template' => 'custom_recent_post',
      ),
      'custom_footer_from_the_blog' => array(
          'variables' => array('nodes' => NULL),
          'template' => 'custom_footer_from_the_blog',
      ),
      'sidebar_categories' => array(
          'variables' => array('terms' => NULL),
          'template' => 'sidebar_categories',
      ),
      'recent_projects' => array(
          'variables' => array('nodes' => NULL, 'title' => NULL),
          'template' => 'recent_projects',
      ),
  );
}

function custom_trim_text($alter, $value) {
  if (drupal_strlen($value) > $alter['max_length']) {
    $value = drupal_substr($value, 0, $alter['max_length']);
    // TODO: replace this with cleanstring of ctools
    if (!empty($alter['word_boundary'])) {
      $regex = "(.*)\b.+";
      if (function_exists('mb_ereg')) {
        mb_regex_encoding('UTF-8');
        $found = mb_ereg($regex, $value, $matches);
      } else {
        $found = preg_match("/$regex/us", $value, $matches);
      }
      if ($found) {
        $value = $matches[1];
      }
    }
    // Remove scraps of HTML entities from the end of a strings
    $value = rtrim(preg_replace('/(?:<(?!.+>)|&(?!.+;)).*$/us', '', $value));

    if (!empty($alter['ellipsis'])) {
      $value .= t('...');
    }
  }
  if (!empty($alter['html'])) {
    $value = _filter_htmlcorrector($value);
  }

  return $value;
}

function custom_format_comma_field($field_category, $node, $link = TRUE, $limit = NULL) {
  $category_arr = array();
  $category = '';
  if (!empty($node->{$field_category}[LANGUAGE_NONE])) {
    foreach ($node->{$field_category}[LANGUAGE_NONE] as $item) {
      $term = taxonomy_term_load($item['tid']);
      if ($term) {
        if ($link) {
          $category_arr[] = l($term->name, 'taxonomy/term/' . $item['tid']);
        } else {
          $category_arr[] = $term->name;
        }
      }

      if ($limit) {
        if (count($category_arr) == $limit) {
          $category = implode(', ', $category_arr);
          return $category;
        }
      }
    }
  }
  $category = implode(', ', $category_arr);

  return $category;
}

function custom_block_get_title($delta) {
  $block = db_query('SELECT title FROM {block} WHERE delta = :delta', array(':delta' => $delta))->fetchObject();

  return $block->title ? $block->title : '';
}
